# Configuração da Engine de Ataque
# Arquivo de configuração principal

# Configurações gerais
general:
  version: "1.0"
  debug: false
  log_level: "INFO"
  max_threads: 100
  default_timeout: 30

# Configurações de ataque
attack:
  # Ataques Low-and-Slow
  slow:
    min_delay: 10
    max_delay: 15
    connection_timeout: 60
    max_connections: 1000
    
  # Ataques de Saturação
  saturation:
    syn_flood:
      enabled: true
      packet_size: 64
      rate_limit: 1000  # pacotes por segundo
    
    udp_flood:
      enabled: true
      packet_size: 1024
      rate_limit: 500
    
    icmp_flood:
      enabled: true
      packet_size: 512
      rate_limit: 200
  
  # Ataques de Exploração
  exploit:
    tcp_reuse:
      enabled: true
      max_connections: 50
      reuse_timeout: 30
    
    slow_headers:
      enabled: true
      header_delay: 15
      max_headers: 10
    
    connection_flood:
      enabled: true
      burst_size: 50
      burst_interval: 5

# Configurações stealth
stealth:
  enabled: false
  min_delay: 100
  max_delay: 500
  jitter: 10
  ip_spoofing: true
  port_randomization: true
  user_agent_rotation: true
  
  # Headers legítimos
  legitimate_headers:
    - "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    - "Accept-Language: en-US,en;q=0.5"
    - "Accept-Encoding: gzip, deflate"
    - "Connection: keep-alive"
    - "Upgrade-Insecure-Requests: 1"

# Configurações de mutação
mutation:
  enabled: false
  mutation_rate: 0.3
  max_mutations: 5
  
  # Padrões de mutação
  patterns:
    - "random_chars"
    - "base64_encode"
    - "xor_encrypt"
    - "compression"
    - "obfuscation"
    - "polymorphism"

# Configurações de análise
analysis:
  enabled: true
  scan_ports: [21, 22, 23, 25, 53, 80, 110, 143, 443, 993, 995, 3306, 3389, 5432, 8080]
  ping_count: 5
  timeout: 5
  
  # Vulnerabilidades para testar
  vulnerabilities:
    - "slow_headers"
    - "connection_limit"
    - "timeout_behavior"

# Configurações de IoC
ioc:
  enabled: true
  formats:
    - "json"
    - "stix"
    - "sigma"
    - "yara"
  
  # Tipos de IoC para gerar
  types:
    - "ip"
    - "domain"
    - "url"
    - "hash"
    - "email"
    - "registry"
    - "file"

# Configurações de logging
logging:
  enabled: true
  file: "engine.log"
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  
  # Logs específicos
  attack_log: "attack.log"
  stealth_log: "stealth.log"
  ioc_log: "ioc.log"

# Configurações de rede
network:
  interface: "eth0"
  source_ip: "auto"  # auto, random, specific
  source_port: "random"
  ttl: 64
  tos: 0
  
  # Configurações de proxy (opcional)
  proxy:
    enabled: false
    type: "http"  # http, socks4, socks5
    host: ""
    port: 0
    username: ""
    password: ""

# Configurações de performance
performance:
  max_memory: "1GB"
  cpu_limit: 80  # porcentagem
  network_buffer: 65536
  
  # Otimizações
  optimizations:
    packet_batching: true
    memory_pool: true
    zero_copy: false

# Configurações de segurança
security:
  # Evitar detecção
  evasion:
    signature_rotation: true
    timing_randomization: true
    payload_obfuscation: true
  
  # Limites de segurança
  limits:
    max_packets_per_second: 10000
    max_connections_per_target: 1000
    max_duration: 3600  # segundos
    
  # Alertas
  alerts:
    high_cpu_usage: 90
    high_memory_usage: 85
    network_saturation: 95

# Configurações de relatórios
reports:
  enabled: true
  format: "json"  # json, xml, csv
  include_timestamps: true
  include_statistics: true
  
  # Campos do relatório
  fields:
    - "target"
    - "attack_type"
    - "duration"
    - "packets_sent"
    - "connections_established"
    - "vulnerabilities_found"
    - "ioc_generated" 